apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - operator-serviceaccount.yaml
  - operator.yaml
  - ts-ingress-nginx-controller-z7ks4.yaml
  - ts-kube-dns-crlgk.yaml
  - my-home-router.yaml
