apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: my-home-router
  namespace: tailscale
spec:
  hostname: k8s-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "192.168.86.0/24"
  exitNode: true
