apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-ingress
  namespace: ray
spec:
  ingressClassName: nginx
  rules:
    - host: ray.homelab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ray-head-svc
                port:
                  number: 8265
