apiVersion: v1
kind: Service
metadata:
  name: ray-head-svc
  namespace: ray
spec:
  selector:
    ray.io/cluster: ray-cluster
    ray.io/node-type: head
  ports:
    - protocol: TCP
      port: 8265
      targetPort: 8265
      name: dashboard
