apiVersion: v1
kind: Service
metadata:
  name: webtop
  namespace: remote-desktop
  labels:
    app: webtop
spec:
  ports:
    - port: 3000
      name: http
      targetPort: 3000
      protocol: TCP
    - port: 22
      name: ssh
      targetPort: 22
      protocol: TCP
  selector:
    app: webtop
