apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remote-dev-vm
  namespace: remote-dev-vm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  rules:
    - host: remote-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: remote-dev-vm
                port:
                  number: 8080
