apiVersion: v1
kind: Service
metadata:
  name: remote-dev-vm
  namespace: remote-dev-vm
spec:
  ports:
    - port: 3000
      targetPort: 6901
      protocol: TCP
      name: http
  selector:
    app: remote-dev-vm
