apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remote-dev-vm
  namespace: remote-dev-vm
  labels:
    app: remote-dev-vm
spec:
  serviceName: remote-dev-vm
  replicas: 1
  selector:
    matchLabels:
      app: remote-dev-vm
  template:
    metadata:
      labels:
        app: remote-dev-vm
    spec:
      containers:
        - name: webtop
          securityContext:
            privileged: true
            seccompProfile:
              type: Unconfined
          image: lscr.io/linuxserver/webtop:alpine-kasm
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: LIBGL_ALWAYS_SOFTWARE
              value: "1"
            - name: CUSTOM_USER
              value: "kyler"
            - name: PASSWORD
              value: "password"
            - name: RESOLUTION
              value: "1920x1080"
            - name: KASM_SVC_bw_quality
              value: "low"
            - name: KASM_SVC_enc_quality
              value: "low"
            - name: KASM_SVC_framerate
              value: "30"
            - name: KASM_SVC_lossless_mode
              value: "true"
            - name: KASM_SVC_resize_mode
              value: "scale"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              cpu: "4000m"
              memory: "16Gi"
            limits:
              cpu: "16000m"
              memory: "32Gi"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 50Gi
