apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remote-dev-vm
  namespace: remote-dev-vm
  labels:
    app: remote-dev-vm
spec:
  serviceName: remote-dev-vm
  replicas: 1
  selector:
    matchLabels:
      app: remote-dev-vm
  template:
    metadata:
      labels:
        app: remote-dev-vm
    spec:
      containers:
        - name: webtop
          securityContext:
            privileged: true
            seccompProfile:
              type: Unconfined
          image: kasmweb/ubuntu-jammy-desktop:1.16.0
          imagePullPolicy: IfNotPresent
          env:
            - name: VNC_PW
              value: "password"
            - name: VNC_USER
              value: "kasm_user"
            - name: VNC_LISTENING_PORT
              value: "-1"
          ports:
            - containerPort: 6901
              name: https
              protocol: TCP
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          readinessProbe:
            tcpSocket:
              port: 6901
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6901
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "4000m"
              memory: "16Gi"
            limits:
              cpu: "16000m"
              memory: "32Gi"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 50Gi
