apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tun-device-plugin
  namespace: kubevirt
  labels:
    app: tun-device-plugin
spec:
  selector:
    matchLabels:
      app: tun-device-plugin
  template:
    metadata:
      labels:
        app: tun-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: device-plugin
          image: ghcr.io/squat/generic-device-plugin:latest
          args:
            - --domain=devices.kubevirt.io
            - --device={"name": "tun", "groups": [{"paths": [{"path": "/dev/net/tun"}]}]}
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
      volumes:
        - name: dev
          hostPath:
            path: /dev
